api1:
    environment:
        - SERVERNAME=api1
    build: ./api
    links:
        - redis
    ports:
        - "8088"
api2:
    environment:
        - SERVERNAME=api2
    build: ./api
    links:
        - redis
    ports:
        - "8088"
client:
    environment:
        - SERVERNAME=client
    build: ./client    
    ports:
        - "8080:80"
redis:
    image: redis
    ports:
        - "6379"
nginx:
    build: ./nginx
    links:
        - api1:node1
        - api2:node2
    ports:
        - "80:80"
