
node1:
    environment:
        - SERVERNAME=node1
    build: ./api
    links:
        - redis
    ports:
        - "8088"
node2:
    environment:
        - SERVERNAME=node2
    build: ./api
    links:
        - redis
    ports:
        - "8088"
node3:
    environment:
        - SERVERNAME=node3
    build: ./api    
    links:
        - redis
    ports:
        - "8088"
client:
    environment:
        - SERVERNAME=client
    build: ./angular-client    
    ports:
        - "80:80"
redis:
    image: redis
    ports:
        - "6379"
nginx:
    build: ./nginx
    links:
        - node1:node1
        - node2:node2
        - node3:node3
    ports:
        - "8080:8080"


        
